authors = ["Gabriel Wu <wuzihua@pku.edu.cn> and contributors"]
name = "StringAlgorithms"
uuid = "643b1d47-3f53-4b81-a7a3-63e902513088"
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "0.8, 0.9"
julia = "1.8"
